const fs = require('fs');

// Extract app glossary from workoutPrompt.ts
const workoutPromptContent = fs.readFileSync('./src/data/workoutPrompt.ts', 'utf8');
const appGlossaryMatch = workoutPromptContent.match(/"exercises":\s*\[([\s\S]*?)\]/);
const appExercises = [];

if (appGlossaryMatch) {
  const exercisesString = appGlossaryMatch[1];
  const matches = exercisesString.match(/"([^"]+)"/g);
  if (matches) {
    appExercises.push(...matches.map(m => m.replace(/"/g, '')));
  }
}

// AI prompt glossary from user's message
const aiPromptExercises = [
  "Barbell Bench Press",
  "Incline Barbell Bench Press",
  "Decline Barbell Bench Press",
  "Close Grip Bench Press",
  "Dumbbell Bench Press",
  "Incline Dumbbell Press",
  "Decline Dumbbell Press",
  "Dumbbell Fly",
  "Incline Dumbbell Fly",
  "Cable Fly",
  "Low Cable Fly",
  "High Cable Fly",
  "Machine Chest Press",
  "Incline Machine Press",
  "Pec Deck",
  "Push Up",
  "Push Ups",
  "Incline Push Up",
  "Incline Push Ups",
  "Decline Push Up",
  "Decline Push Ups",
  "Diamond Push Up",
  "Diamond Push Ups",
  "Dip",
  "Dips",
  "Chest Dip",
  "Chest Dips",
  "Smith Machine Bench Press",
  "Smith Machine Incline Press",
  "Svend Press",
  "Landmine Press",
  "Pull Up",
  "Pull Ups",
  "Chin Up",
  "Chin Ups",
  "Neutral Grip Pull Up",
  "Neutral Grip Pull Ups",
  "Wide Grip Pull Up",
  "Wide Grip Pull Ups",
  "Assisted Pull Up",
  "Assisted Pull Ups",
  "Lat Pulldown",
  "Wide Grip Lat Pulldown",
  "Close Grip Lat Pulldown",
  "Neutral Grip Lat Pulldown",
  "Reverse Grip Lat Pulldown",
  "Straight Arm Pulldown",
  "Barbell Row",
  "Pendlay Row",
  "Underhand Barbell Row",
  "Dumbbell Row",
  "Dumbbell Row (Two Arm)",
  "Chest Supported Row",
  "Seal Row",
  "T-Bar Row",
  "Cable Row",
  "Wide Grip Cable Row",
  "Single Arm Cable Row",
  "Machine Row",
  "Meadows Row",
  "Inverted Row",
  "Smith Machine Row",
  "Kroc Row",
  "Deadlift",
  "Conventional Deadlift",
  "Sumo Deadlift",
  "Romanian Deadlift",
  "Dumbbell Romanian Deadlift",
  "Single Leg Romanian Deadlift",
  "Stiff Leg Deadlift",
  "Deficit Deadlift",
  "Trap Bar Deadlift",
  "Rack Pull",
  "Block Pull",
  "Good Morning",
  "Hyperextension",
  "Reverse Hyperextension",
  "Back Extension",
  "Barbell Shrug",
  "Dumbbell Shrug",
  "Trap Bar Shrug",
  "Cable Shrug",
  "Face Pull",
  "Overhead Press",
  "Military Press",
  "Push Press",
  "Seated Barbell Press",
  "Behind Neck Press",
  "Dumbbell Shoulder Press",
  "Seated Dumbbell Press",
  "Arnold Press",
  "Machine Shoulder Press",
  "Smith Machine Shoulder Press",
  "Lateral Raise",
  "Lateral Raises",
  "Cable Lateral Raise",
  "Cable Lateral Raises",
  "Machine Lateral Raise",
  "Machine Lateral Raises",
  "Leaning Lateral Raise",
  "Leaning Lateral Raises",
  "Front Raise",
  "Barbell Front Raise",
  "Cable Front Raise",
  "Plate Front Raise",
  "Rear Delt Fly",
  "Cable Rear Delt Fly",
  "Machine Rear Delt Fly",
  "Incline Rear Delt Fly",
  "Upright Row",
  "Dumbbell Upright Row",
  "Cable Upright Row",
  "Lu Raise",
  "Bus Driver",
  "Barbell Curl",
  "Barbell Curls",
  "EZ Bar Curl",
  "EZ Bar Curls",
  "Dumbbell Curl",
  "Dumbbell Curls",
  "Alternating Dumbbell Curl",
  "Alternating Dumbbell Curls",
  "Incline Dumbbell Curl",
  "Incline Dumbbell Curls",
  "Concentration Curl",
  "Concentration Curls",
  "Preacher Curl",
  "Preacher Curls",
  "Dumbbell Preacher Curl",
  "Dumbbell Preacher Curls",
  "Machine Preacher Curl",
  "Cable Curl",
  "High Cable Curl",
  "Bayesian Cable Curl",
  "Hammer Curl",
  "Hammer Curls",
  "Rope Hammer Curl",
  "Rope Hammer Curls",
  "Cross Body Hammer Curl",
  "Cross Body Hammer Curls",
  "Reverse Curl",
  "EZ Bar Reverse Curl",
  "Zottman Curl",
  "Spider Curl",
  "Drag Curl",
  "21s",
  "Tricep Pushdown",
  "Tricep Pushdowns",
  "Rope Pushdown",
  "Rope Pushdowns",
  "Straight Bar Pushdown",
  "Straight Bar Pushdowns",
  "V-Bar Pushdown",
  "V-Bar Pushdowns",
  "Reverse Grip Pushdown",
  "Reverse Grip Pushdowns",
  "Overhead Tricep Extension",
  "Overhead Tricep Extensions",
  "Overhead Cable Extension",
  "Overhead Cable Extensions",
  "Skull Crusher",
  "Skull Crushers",
  "Dumbbell Skull Crusher",
  "Dumbbell Skull Crushers",
  "Incline Skull Crusher",
  "Incline Skull Crushers",
  "Tricep Kickback",
  "Tricep Kickbacks",
  "Cable Tricep Kickback",
  "Cable Tricep Kickbacks",
  "Tricep Dip",
  "Tricep Dips",
  "Bench Dip",
  "Bench Dips",
  "Close Grip Push Up",
  "JM Press",
  "French Press",
  "Tate Press",
  "Machine Tricep Extension",
  "Machine Dip",
  "Barbell Back Squat",
  "High Bar Squat",
  "Low Bar Squat",
  "Front Squat",
  "Goblet Squat",
  "Dumbbell Squat",
  "Hack Squat",
  "Leg Press",
  "Leg Press (High Foot)",
  "Leg Press (Low Foot)",
  "Single Leg Press",
  "Smith Machine Squat",
  "Pendulum Squat",
  "Belt Squat",
  "Box Squat",
  "Pause Squat",
  "Zercher Squat",
  "Sissy Squat",
  "Leg Extension",
  "Single Leg Extension",
  "Lunge",
  "Dumbbell Lunge",
  "Barbell Lunge",
  "Walking Lunge",
  "Dumbbell Walking Lunge",
  "Reverse Lunge",
  "Dumbbell Reverse Lunge",
  "Deficit Reverse Lunge",
  "Bulgarian Split Squat",
  "Dumbbell Bulgarian Split Squat",
  "Barbell Bulgarian Split Squat",
  "Step Up",
  "Dumbbell Step Up",
  "Barbell Step Up",
  "Lateral Lunge",
  "Curtsy Lunge",
  "Leg Curl",
  "Leg Curls",
  "Lying Leg Curl",
  "Lying Leg Curls",
  "Seated Leg Curl",
  "Seated Leg Curls",
  "Single Leg Curl",
  "Single Leg Curls",
  "Nordic Curl",
  "Glute Ham Raise",
  "Dumbbell Leg Curl",
  "Cable Leg Curl",
  "Slider Leg Curl",
  "Swiss Ball Leg Curl",
  "Hip Thrust",
  "Dumbbell Hip Thrust",
  "Single Leg Hip Thrust",
  "Machine Hip Thrust",
  "Glute Bridge",
  "Barbell Glute Bridge",
  "Single Leg Glute Bridge",
  "Cable Pull Through",
  "Kettlebell Swing",
  "Cable Glute Kickback",
  "Machine Kickback",
  "Donkey Kick",
  "Fire Hydrant",
  "Hip Abduction Machine",
  "Hip Adduction Machine",
  "Cable Hip Abduction",
  "Cable Hip Adduction",
  "Clamshell",
  "Frog Pump",
  "Standing Calf Raise",
  "Standing Calf Raises",
  "Seated Calf Raise",
  "Seated Calf Raises",
  "Leg Press Calf Raise",
  "Leg Press Calf Raises",
  "Smith Machine Calf Raise",
  "Smith Machine Calf Raises",
  "Dumbbell Calf Raise",
  "Dumbbell Calf Raises",
  "Single Leg Calf Raise",
  "Single Leg Calf Raises",
  "Donkey Calf Raise",
  "Donkey Calf Raises",
  "Tibialis Raise",
  "Crunch",
  "Cable Crunch",
  "Machine Crunch",
  "Decline Crunch",
  "Reverse Crunch",
  "Sit Up",
  "Sit Ups",
  "Decline Sit Up",
  "Decline Sit Ups",
  "Weighted Sit Up",
  "Weighted Sit Ups",
  "Hanging Leg Raise",
  "Hanging Knee Raise",
  "Captain's Chair Leg Raise",
  "Lying Leg Raise",
  "Plank",
  "Side Plank",
  "RKC Plank",
  "Ab Rollout",
  "Barbell Rollout",
  "Russian Twist",
  "Weighted Russian Twist",
  "Cable Woodchop",
  "High to Low Woodchop",
  "Low to High Woodchop",
  "Pallof Press",
  "Dead Bug",
  "Bird Dog",
  "Mountain Climber",
  "Bicycle Crunch",
  "V-Up",
  "Toe Touch",
  "Hollow Hold",
  "L-Sit",
  "Dragon Flag",
  "Suitcase Carry",
  "Farmer's Walk",
  "Wrist Curl",
  "Dumbbell Wrist Curl",
  "Reverse Wrist Curl",
  "Behind Back Wrist Curl",
  "Plate Pinch",
  "Gripper",
  "Dead Hang",
  "Bench Press (Pause)",
  "Spoto Press",
  "Floor Press",
  "Dumbbell Floor Press",
  "Board Press",
  "Pin Press",
  "Larsen Press",
  "Tempo Bench Press",
  "Paused Squat",
  "Tempo Squat",
  "1.5 Rep Squat",
  "Anderson Squat",
  "Safety Bar Squat",
  "Paused Deadlift",
  "Tempo Deadlift",
  "Snatch Grip Deadlift",
  "Jefferson Deadlift",
  "Reeves Deadlift",
  "Cable Face Pull",
  "Romanian Dumbbell Deadlift",
  "Seated Dumbbell Shoulder Press",
  "Dumbbell Bicep Curl",
  "Tricep Rope Pushdown",
  "Overhead Tricep Extension (Cable)",
  "Knee Plank",
  "Wall Plank",
  "Wall Push Up",
  "Wall Push Ups",
  "Wall Sit",
  "Chair Squat",
  "Bodyweight Squat",
  "Assisted Squat",
  "Knee Push Up",
  "Knee Push Ups",
  "Glute Kickback",
  "Side-lying Hip Abduction",
  "Lateral Band Walks",
  "Resistance Band Squat",
  "Resistance Band Row",
  "Resistance Band Lateral Raise",
  "Resistance Band Shoulder Press",
  "Squat Pulse",
  "Squat Hold",
  "Squat to Calf Raise",
  "Single Leg Squat",
  "Pistol Squat",
  "Wood Chop",
  "High to Low Chop",
  "Low to High Chop",
  "Bear Crawl",
  "Crab Walk",
  "High Knees",
  "Butt Kickers",
  "Jumping Jacks",
  "Jump Squat",
  "Reverse Fly",
  "Stability Ball Crunch",
  "Stability Ball Plank",
  "Cat Cow",
  "Child's Pose Hold",
  "Hip Flexor Stretch",
  "Calf Stretch",
  "Quad Stretch",
  "Hamstring Stretch"
];

// Compare the arrays
const appSet = new Set(appExercises);
const aiSet = new Set(aiPromptExercises);

const inAiNotInApp = aiPromptExercises.filter(ex => !appSet.has(ex));
const inAppNotInAi = appExercises.filter(ex => !aiSet.has(ex));

console.log('=== EXERCISE GLOSSARY COMPARISON ===\n');
console.log(`App Glossary Total: ${appExercises.length} exercises`);
console.log(`AI Prompt Glossary Total: ${aiPromptExercises.length} exercises\n`);

console.log('=== EXERCISES IN AI PROMPT BUT NOT IN APP ===');
console.log(`Count: ${inAiNotInApp.length}`);
if (inAiNotInApp.length > 0) {
  inAiNotInApp.forEach(ex => console.log(`  - "${ex}"`));
} else {
  console.log('  None');
}

console.log('\n=== EXERCISES IN APP BUT NOT IN AI PROMPT ===');
console.log(`Count: ${inAppNotInAi.length}`);
if (inAppNotInAi.length > 0) {
  inAppNotInAi.forEach(ex => console.log(`  - "${ex}"`));
} else {
  console.log('  None');
}

console.log('\n=== RECOMMENDATIONS ===');
if (inAiNotInApp.length > 0) {
  console.log('❌ ISSUE: AI prompt contains exercises not in your app. This will cause import failures.');
  console.log('   FIX: Either add these to your app glossary or remove from AI prompt.');
}
if (inAppNotInAi.length > 0) {
  console.log('⚠️  NOTE: Your app supports exercises not in the AI prompt. Claude won\'t use these.');
  console.log('   OPTIONAL: Add these to AI prompt if you want Claude to use them.');
}
if (inAiNotInApp.length === 0) {
  console.log('✅ All AI prompt exercises exist in your app glossary.');
}