import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // ── Container ────────────────────────────────────────────────────
  container: {
    flex: 1,
    backgroundColor: '#000',
  },

  // ── Header ───────────────────────────────────────────────────────
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#0a0a0f',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
  },
  blockLabel: {
    fontSize: 10,
    fontWeight: '500',
    color: '#55555f',
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    marginBottom: 2,
    fontFamily: 'DMMono-Medium',
  },
  blockPhase: {
    fontSize: 16,
    fontWeight: '600',
    color: '#f0f0f2',
    letterSpacing: -0.2,
    fontFamily: 'Outfit-SemiBold',
  },

  // ── List ─────────────────────────────────────────────────────────
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 16,
  },

  // ── Card (incomplete day) ────────────────────────────────────────
  card: {
    backgroundColor: '#0a0a0f',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    borderLeftWidth: 3,
    padding: 16,
    marginBottom: 10,
  },

  // ── Card (completed) ─────────────────────────────────────────────
  cardCompleted: {
    backgroundColor: '#0a0a0f',
    borderColor: 'rgba(34,211,238,0.18)',
    padding: 14,
  },
  completedCardContent: {
    alignItems: 'stretch',
  },
  completedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    gap: 10,
  },
  completedTitleContainer: {
    flex: 1,
    alignItems: 'flex-start',
  },
  completedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(34,211,238,0.12)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    gap: 4,
  },
  completedBadgeText: {
    fontSize: 9,
    fontWeight: '600',
    color: '#22d3ee',
    letterSpacing: 1.3,
    fontFamily: 'DMMono-Medium',
  },
  completedStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 14,
  },
  completedStat: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  completedStatValue: {
    fontSize: 18,
    fontWeight: '600',
    color: '#f0f0f2',
    letterSpacing: -0.3,
    fontFamily: 'Outfit-SemiBold',
  },
  completedStatLabel: {
    fontSize: 10,
    fontWeight: '500',
    color: '#55555f',
    letterSpacing: 1.3,
    fontFamily: 'DMMono-Regular',
  },
  completedStatDivider: {
    width: 1,
    height: 18,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  redoButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#0a0a0f',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // ── Card header ──────────────────────────────────────────────────
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  cardTitle: {
    flex: 1,
  },
  dayNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  dayName: {
    fontSize: 19,
    fontWeight: '700',
    color: '#f0f0f2',
    lineHeight: 24,
    letterSpacing: -0.4,
    fontFamily: 'Outfit-Bold',
  },
  dayNameCompleted: {
    fontSize: 16,
    fontWeight: '600',
    color: '#f0f0f2',
    lineHeight: 20,
    letterSpacing: -0.2,
    fontFamily: 'Outfit-SemiBold',
  },
  checkIcon: {
    marginLeft: 8,
  },
  completionInfo: {
    marginBottom: 4,
  },
  completionInfoText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#22d3ee',
    marginBottom: 2,
    fontFamily: 'Outfit-Medium',
  },
  completionDate: {
    fontSize: 11,
    color: '#55555f',
    fontFamily: 'DMMono-Regular',
  },
  dayBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  dayBadgeText: {
    fontSize: 9,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 1.3,
    fontFamily: 'DMMono-Medium',
  },
  startButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 9,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 5,
    backgroundColor: 'rgba(34,211,238,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(34,211,238,0.3)',
  },
  startButtonText: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 1.3,
    fontFamily: 'DMMono-Medium',
  },
  completedButton: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderColor: 'rgba(255,255,255,0.06)',
  },
  completedButtonText: {
    color: '#55555f',
  },

  // ── Week navigation ──────────────────────────────────────────────
  weekNavigationContainer: {
    marginBottom: 14,
    paddingTop: 4,
  },
  weekNavigation: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: '#0a0a0f',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  weekNavButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  weekNavButtonDisabled: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(255,255,255,0.03)',
  },
  weekDisplay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  weekHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  weekLabel: {
    fontSize: 10,
    color: '#55555f',
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    fontWeight: '500',
    fontFamily: 'DMMono-Medium',
  },
  bookmarkButton: {
    padding: 2,
  },
  bookmarkIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingTop: 10,
    paddingBottom: 2,
  },
  bookmarkText: {
    fontSize: 10,
    color: '#f7b220',
    fontWeight: '500',
    letterSpacing: 0.3,
    fontFamily: 'Outfit-Medium',
  },
  weekNumberContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 8,
  },
  weekNumber: {
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: -0.6,
    fontFamily: 'Outfit-Bold',
  },
  weekTotal: {
    fontSize: 14,
    color: '#55555f',
    marginLeft: 4,
    fontFamily: 'Outfit-Regular',
  },
  weekProgress: {
    width: 120,
    height: 3,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  weekProgressFill: {
    height: '100%',
    borderRadius: 2,
  },

  // ── Completion stats (inline) ────────────────────────────────────
  completionStats: {
    backgroundColor: 'rgba(34,211,238,0.04)',
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: 'rgba(34,211,238,0.18)',
  },
  completionStatsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 6,
  },
  completionStatsTitle: {
    fontSize: 10,
    fontWeight: '500',
    color: '#22d3ee',
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    fontFamily: 'DMMono-Medium',
  },
  completionStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  completionStat: {
    alignItems: 'center',
  },
  completionStatValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#f0f0f2',
    marginBottom: 2,
    fontFamily: 'Outfit-SemiBold',
  },
  completionStatLabel: {
    fontSize: 9,
    color: '#55555f',
    textTransform: 'uppercase',
    letterSpacing: 1.3,
    fontFamily: 'DMMono-Regular',
  },

  // ── Card body ────────────────────────────────────────────────────
  cardBody: {
    gap: 12,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 18,
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  statText: {
    fontSize: 12,
    color: '#9898a4',
    fontWeight: '500',
    fontFamily: 'Outfit-Medium',
  },
  exerciseGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  exerciseChip: {
    backgroundColor: '#111116',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    minWidth: 100,
    maxWidth: '48%',
  },
  exerciseChipText: {
    fontSize: 11,
    color: '#f0f0f2',
    fontWeight: '500',
    marginBottom: 2,
    fontFamily: 'Outfit-Medium',
  },
  exerciseChipSets: {
    fontSize: 10,
    fontWeight: '500',
    fontFamily: 'DMMono-Medium',
    letterSpacing: 0.2,
  },
  moreChip: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 40,
    borderStyle: 'dashed',
  },
  moreChipText: {
    fontSize: 11,
    color: '#55555f',
    fontWeight: '500',
    fontFamily: 'DMMono-Medium',
    letterSpacing: 0.3,
  },

  // ── Add day button ───────────────────────────────────────────────
  addDayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    marginVertical: 4,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderRadius: 12,
    backgroundColor: 'transparent',
    gap: 8,
  },
  addDayText: {
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0.3,
    fontFamily: 'Outfit-Medium',
  },

  // ── Dark modal (basic, used for Android Add Day) ─────────────────
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    padding: 32,
  },
  modal: {
    backgroundColor: '#0a0a0f',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  title: {
    fontSize: 18,
    fontWeight: '600',
    color: '#f0f0f2',
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Outfit-SemiBold',
  },
  input: {
    backgroundColor: '#111116',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 11,
    padding: 14,
    fontSize: 15,
    color: '#f0f0f2',
    marginBottom: 24,
    fontFamily: 'Outfit-Regular',
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  buttonWrapper: {
    flex: 1,
    borderRadius: 8,
    overflow: 'hidden',
  },

  // ── "New" modal variant (legacy alt modal) ───────────────────────
  newModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-end',
  },
  newModalBackdrop: {
    flex: 1,
  },
  newModalContainer: {
    backgroundColor: '#0a0a0f',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 32,
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  newModalHandle: {
    width: 36,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 6,
  },
  newModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  newModalTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: '#f0f0f2',
    flex: 1,
    letterSpacing: -0.3,
    fontFamily: 'Outfit-Bold',
  },
  newModalCloseButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  newModalContent: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    alignItems: 'center',
  },
  newModalIconWrapper: {
    marginBottom: 20,
  },
  newModalIconBg: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  newModalDescription: {
    fontSize: 14,
    color: '#9898a4',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
    paddingHorizontal: 8,
    fontFamily: 'Outfit-Regular',
  },
  newInputSection: {
    width: '100%',
  },
  newInputLabel: {
    fontSize: 10,
    fontWeight: '500',
    color: '#9898a4',
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    fontFamily: 'DMMono-Medium',
  },
  newModalInput: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#f0f0f2',
    marginBottom: 6,
    backgroundColor: '#111116',
    fontFamily: 'Outfit-Regular',
  },
  newCharacterCount: {
    fontSize: 11,
    color: '#55555f',
    textAlign: 'right',
    marginBottom: 14,
    fontFamily: 'DMMono-Regular',
  },
  newModalActions: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 6,
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.05)',
  },
  newCancelButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
  },
  newCreateButton: {
    flex: 1.4,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
  },
  newCancelText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#9898a4',
    fontFamily: 'Outfit-Medium',
  },
  newCreateText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
    fontFamily: 'Outfit-SemiBold',
  },

  // ── Exercise management modal ────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
  },
  modalBackdrop: {
    flex: 1,
  },
  modalContainer: {
    backgroundColor: '#0a0a0f',
    borderRadius: 20,
    height: '80%',
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    flex: 0,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  modalHandle: {
    width: 32,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 2,
    position: 'absolute',
    top: 8,
    left: '50%',
    marginLeft: -16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#f0f0f2',
    flex: 1,
    textAlign: 'center',
    letterSpacing: -0.3,
    fontFamily: 'Outfit-SemiBold',
  },
  modalCloseButton: {
    width: 34,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  modalContent: {
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 8,
  },
  modalIconContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  modalIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalSubtitle: {
    fontSize: 13,
    color: '#9898a4',
    lineHeight: 19,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Outfit-Regular',
  },
  inputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: '500',
    color: '#9898a4',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    fontFamily: 'DMMono-Medium',
  },
  modalInput: {
    backgroundColor: '#111116',
    borderRadius: 11,
    padding: 14,
    fontSize: 15,
    color: '#f0f0f2',
    borderWidth: 1,
    marginBottom: 4,
    fontFamily: 'Outfit-Regular',
  },
  characterCount: {
    fontSize: 11,
    color: '#55555f',
    textAlign: 'right',
    fontFamily: 'DMMono-Regular',
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.05)',
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  modalCreateButton: {
    flex: 1.5,
    flexDirection: 'row',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    gap: 6,
  },
  modalCancelText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#9898a4',
    textAlign: 'center',
    flexShrink: 1,
    fontFamily: 'Outfit-Medium',
  },
  modalCreateText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
    flexShrink: 1,
    fontFamily: 'Outfit-SemiBold',
  },

  // ── Exercise list inside modal ───────────────────────────────────
  modalScrollContent: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 14,
    flex: 1,
  },
  exerciseListContainer: {
    marginTop: 20,
  },
  exerciseListLabel: {
    fontSize: 10,
    fontWeight: '500',
    color: '#9898a4',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    fontFamily: 'DMMono-Medium',
  },
  exerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111116',
    borderRadius: 11,
    padding: 14,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    minHeight: 56,
  },
  dragHandle: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  exerciseContent: {
    flex: 1,
  },
  exerciseName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#f0f0f2',
    fontFamily: 'Outfit-Medium',
  },
  moveButtons: {
    flexDirection: 'column',
    gap: 2,
  },
  moveButton: {
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 7,
  },
  moveButtonDisabled: {
    backgroundColor: 'transparent',
  },

  // ── Rest day card ────────────────────────────────────────────────
  restDayName: {
    color: '#55555f',
  },
  restDayCard: {
    backgroundColor: '#0a0a0f',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.04)',
    borderLeftWidth: 3,
    padding: 18,
    marginBottom: 10,
  },
  restDayContent: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 6,
  },
  restDayTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#9898a4',
    marginTop: 6,
    letterSpacing: -0.2,
    fontFamily: 'Outfit-SemiBold',
  },
  restDaySubtitle: {
    fontSize: 11,
    fontWeight: '500',
    color: '#55555f',
    letterSpacing: 1.3,
    textTransform: 'uppercase',
    fontFamily: 'DMMono-Medium',
  },

  // ── Rest toggle (header) ─────────────────────────────────────────
  restToggle: {
    alignItems: 'center',
    gap: 4,
  },
  restToggleTrack: {
    width: 30,
    height: 17,
    borderRadius: 9,
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  restToggleThumb: {
    width: 13,
    height: 13,
    borderRadius: 7,
  },
  restToggleLabel: {
    fontSize: 9,
    fontWeight: '500',
    color: '#55555f',
    textTransform: 'uppercase',
    letterSpacing: 1.3,
    fontFamily: 'DMMono-Medium',
  },

  // ── Volume overview ──────────────────────────────────────────────
  volumeToggle: {
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 11,
    backgroundColor: '#0a0a0f',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  volumeToggleContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  volumeToggleText: {
    fontSize: 11,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    fontFamily: 'DMMono-Medium',
  },
  volumeOverview: {
    marginTop: 10,
    padding: 14,
    backgroundColor: '#0a0a0f',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    position: 'relative',
  },
  volumeContent: {
    gap: 18,
  },
  bodyDiagramContainer: {
    alignItems: 'center',
    paddingVertical: 14,
    backgroundColor: '#000',
    borderRadius: 11,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.04)',
    position: 'relative',
  },
  bodyDiagramHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingHorizontal: 14,
  },
  bodyDiagramTitle: {
    fontSize: 10,
    fontWeight: '500',
    color: '#9898a4',
    flex: 1,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    fontFamily: 'DMMono-Medium',
  },
  bodyFlipIcon: {
    width: 30,
    height: 30,
    borderRadius: 9,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  volumeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
  },
  volumeItem: {
    alignItems: 'center',
    minWidth: 58,
    maxWidth: 78,
    gap: 3,
    flex: 1,
    flexBasis: '22%',
  },
  volumeBar: {
    width: 30,
    height: 30,
    borderRadius: 9,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  volumeNumber: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f0f0f2',
    marginTop: 2,
    fontFamily: 'Outfit-SemiBold',
    letterSpacing: -0.2,
  },
  volumeMuscle: {
    fontSize: 10,
    fontWeight: '500',
    color: '#9898a4',
    textAlign: 'center',
    fontFamily: 'Outfit-Medium',
  },
  volumeEmptyText: {
    fontSize: 12,
    color: '#55555f',
    textAlign: 'center',
    fontStyle: 'italic',
    fontFamily: 'Outfit-Regular',
  },
});