import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // ── Container ────────────────────────────────────────────────────
  container: {
    flex: 1,
    backgroundColor: '#000',
  },

  // ── Header ───────────────────────────────────────────────────────
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#0a0a0f',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerLabel: {
    fontSize: 10,
    color: '#9898a4',
    letterSpacing: 1.4,
    fontFamily: 'DMMono-Medium',
  },
  restToggleButton: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#0a0a0f',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // ── Title block ──────────────────────────────────────────────────
  titleBlock: {
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 18,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  weekTitle: {
    color: '#f0f0f2',
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: -0.5,
    fontFamily: 'Outfit-Bold',
    lineHeight: 30,
  },
  bookmarkButton: {
    width: 32,
    height: 32,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  weekSubtitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  weekSubtitle: {
    color: '#55555f',
    fontSize: 10,
    letterSpacing: 1.3,
    fontFamily: 'DMMono-Medium',
  },
  bookmarkPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 5,
    backgroundColor: 'rgba(247,178,32,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(247,178,32,0.3)',
  },
  bookmarkPillText: {
    fontSize: 8,
    letterSpacing: 1.2,
    color: '#f7b220',
    fontFamily: 'DMMono-Medium',
  },
  weekProgressTrack: {
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 2,
    marginTop: 12,
    overflow: 'hidden',
  },
  weekProgressFill: {
    height: '100%',
    borderRadius: 2,
  },

  // ── Week pager row ───────────────────────────────────────────────
  weekPagerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  weekPagerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  weekPagerButton: {
    width: 26,
    height: 26,
    borderRadius: 7,
    backgroundColor: '#0a0a0f',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekPagerButtonDisabled: {
    opacity: 0.35,
  },
  weekPagerLabel: {
    fontSize: 10,
    color: '#9898a4',
    letterSpacing: 1.3,
    fontFamily: 'DMMono-Medium',
  },
  volumeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(34,211,238,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(34,211,238,0.25)',
  },
  volumeButtonText: {
    fontSize: 10,
    letterSpacing: 1.2,
    fontFamily: 'DMMono-Medium',
    fontWeight: '600',
  },

  // ── Section labels ───────────────────────────────────────────────
  sectionLabel: {
    fontSize: 10,
    letterSpacing: 1.4,
    fontFamily: 'DMMono-Medium',
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  sectionLabelMuted: {
    color: '#55555f',
  },
  sectionLabelAccent: {
    color: '#22d3ee',
  },

  // ── NEXT UP hero card ────────────────────────────────────────────
  nextUpCard: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
    marginBottom: 18,
  },
  nextUpContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  nextUpTextBlock: {
    flex: 1,
  },
  nextUpDayName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#f0f0f2',
    letterSpacing: -0.3,
    fontFamily: 'Outfit-SemiBold',
    marginBottom: 4,
  },
  nextUpMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  nextUpMetaText: {
    fontSize: 11,
    color: '#9898a4',
    fontFamily: 'Outfit-Regular',
  },
  nextUpMetaDot: {
    width: 3,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#3a3a44',
  },
  nextUpStartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 9,
  },
  nextUpStartButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#000',
    fontFamily: 'Outfit-SemiBold',
    letterSpacing: -0.1,
  },

  // ── Day rows (compact) ───────────────────────────────────────────
  dayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#0a0a0f',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    marginBottom: 8,
  },
  dayRowStatus: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayRowStatusNumber: {
    fontSize: 13,
    color: '#9898a4',
    fontFamily: 'DMMono-Medium',
    fontWeight: '600',
  },
  dayRowContent: {
    flex: 1,
    gap: 4,
  },
  dayRowName: {
    fontSize: 17,
    fontWeight: '600',
    color: '#f0f0f2',
    fontFamily: 'Outfit-SemiBold',
    letterSpacing: -0.3,
  },
  dayRowMeta: {
    fontSize: 11,
    color: '#9898a4',
    fontFamily: 'DMMono-Regular',
    letterSpacing: 0.3,
  },

  // ── Rest row (collapsed/muted) ───────────────────────────────────
  restRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 6,
    opacity: 0.55,
  },
  restIconWrap: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  restText: {
    fontSize: 14,
    color: '#9898a4',
    fontFamily: 'Outfit-Medium',
  },
  restDayNameText: {
    fontSize: 10,
    color: '#55555f',
    fontFamily: 'DMMono-Regular',
    letterSpacing: 0.3,
  },

  // ── List ─────────────────────────────────────────────────────────
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 24,
  },

  // ── Add day button ───────────────────────────────────────────────
  addDayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 13,
    marginTop: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderRadius: 12,
    backgroundColor: 'transparent',
    gap: 8,
  },
  addDayText: {
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0.2,
    fontFamily: 'Outfit-Medium',
  },

  // ── Dark modal (Android Add Day) ─────────────────────────────────
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    padding: 32,
  },
  modal: {
    backgroundColor: '#0a0a0f',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  title: {
    fontSize: 18,
    fontWeight: '600',
    color: '#f0f0f2',
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Outfit-SemiBold',
  },
  input: {
    backgroundColor: '#111116',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 11,
    padding: 14,
    fontSize: 15,
    color: '#f0f0f2',
    marginBottom: 24,
    fontFamily: 'Outfit-Regular',
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  buttonWrapper: {
    flex: 1,
    borderRadius: 8,
    overflow: 'hidden',
  },

  // ── Exercise management modal ────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
  },
  modalBackdrop: {
    flex: 1,
  },
  modalContainer: {
    backgroundColor: '#0a0a0f',
    borderRadius: 20,
    height: '80%',
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    flex: 0,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  modalHandle: {
    width: 32,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 2,
    position: 'absolute',
    top: 8,
    left: '50%',
    marginLeft: -16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#f0f0f2',
    flex: 1,
    textAlign: 'center',
    letterSpacing: -0.3,
    fontFamily: 'Outfit-SemiBold',
  },
  modalCloseButton: {
    width: 34,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  modalScrollContent: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 14,
    flex: 1,
  },
  modalSubtitle: {
    fontSize: 13,
    color: '#9898a4',
    lineHeight: 19,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Outfit-Regular',
  },
  inputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: '500',
    color: '#9898a4',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    fontFamily: 'DMMono-Medium',
  },
  modalInput: {
    backgroundColor: '#111116',
    borderRadius: 11,
    padding: 14,
    fontSize: 15,
    color: '#f0f0f2',
    borderWidth: 1,
    marginBottom: 4,
    fontFamily: 'Outfit-Regular',
  },
  characterCount: {
    fontSize: 11,
    color: '#55555f',
    textAlign: 'right',
    fontFamily: 'DMMono-Regular',
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.05)',
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  modalCreateButton: {
    flex: 1.5,
    flexDirection: 'row',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    gap: 6,
  },
  modalCancelText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#9898a4',
    textAlign: 'center',
    flexShrink: 1,
    fontFamily: 'Outfit-Medium',
  },
  modalCreateText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
    flexShrink: 1,
    fontFamily: 'Outfit-SemiBold',
  },

  // ── Exercise list inside management modal ────────────────────────
  exerciseListContainer: {
    marginTop: 20,
  },
  exerciseListLabel: {
    fontSize: 10,
    fontWeight: '500',
    color: '#9898a4',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    fontFamily: 'DMMono-Medium',
  },
  exerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111116',
    borderRadius: 11,
    padding: 14,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    minHeight: 56,
  },
  dragHandle: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  exerciseContent: {
    flex: 1,
  },
  exerciseName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#f0f0f2',
    fontFamily: 'Outfit-Medium',
  },
  moveButtons: {
    flexDirection: 'column',
    gap: 2,
  },
  moveButton: {
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 7,
  },
  moveButtonDisabled: {
    backgroundColor: 'transparent',
  },
});